name       : perl-glib-object-introspection
version    : 0.044
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/X/XA/XAOC/Glib-Object-Introspection-0.044.tar.gz : 093c47141db683bf8dcbf1c3e7b2ece2b2b5488739197b8b623f50838eb7e734
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Glib::Object::Introspection - Dynamically create Perl language bindings
description: |
    Glib::Object::Introspection uses the gobject-introspection and libffi projects to dynamically create Perl bindings for a wide variety of libraries.  Examples include gtk+, webkit, libsoup and many more.
builddeps  :
    - pkgconfig(cairo)
    - perl-cairo-gobject
    - perl-extutils-depends
    - perl-extutils-pkgconfig
    - perl-glib
    - perl-test-simple
rundeps    :
    - perl-cairo-gobject
    - perl-glib
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
