name       : perl-glib-object-introspection
version    : '0.045'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/X/XA/XAOC/Glib-Object-Introspection-0.045.tar.gz : 5f0b88d5cf9b9d5d60c90ea9d411076bea54a2c0757c8f4d527520e5f332e7bb
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Glib::Object::Introspection - Dynamically create Perl language bindings
description: |
    Glib::Object::Introspection uses the gobject-introspection and libffi projects to dynamically create Perl bindings for a wide variety of libraries.  Examples include gtk+, webkit, libsoup and many more.
builddeps  :
    - pkgconfig(cairo)
    - perl-cairo-gobject
    - perl-extutils-depends
    - perl-extutils-pkgconfig
    - perl-glib
    - perl-test-simple
rundeps    :
    - perl-cairo-gobject
    - perl-glib
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
