name       : perl-glib-object-introspection
version    : '0.050'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/X/XA/XAOC/Glib-Object-Introspection-0.050.tar.gz : ecf3bbb824df5eed6a3a7fcfd61be9ef448519801badcc82a6e3c4daab0cd763
homepage   : https://metacpan.org/pod/Glib::Object::Introspection
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Glib::Object::Introspection - Dynamically create Perl language bindings
description: |
    Glib::Object::Introspection uses the gobject-introspection and libffi projects to dynamically create Perl bindings for a wide variety of libraries.  Examples include gtk+, webkit, libsoup and many more.
builddeps  :
    - pkgconfig(cairo)
    - perl-cairo-gobject
    - perl-extutils-depends
    - perl-extutils-pkgconfig
    - perl-glib
    - perl-test-simple
rundeps    :
    - perl-cairo-gobject
    - perl-glib
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
